In [1]:

array4=[23,45,37,32]
print (array4)

[23, 45, 37, 32]


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
arr3=np.array([1,2,3,4,5])
print(arr3)

[1 2 3 4 5]


In [18]:
print(type(arr3))

<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)

In [ ]:
import numpy as np
arr2=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr2)

In [ ]:
import numpy as np
arr2=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr2)

In [ ]:
print(arr1.ndim)

In [ ]:
print(arr2.ndim)

In [ ]:
print(arr3
      .ndim)

In [ ]:
print(arr2[0,1,2])

In [ ]:
print(arr2[1,1,1])

In [20]:
import numpy as np
arr3=np.array([1,2,3,4,5])
print(arr3[1:4])

[2 3 4]


In [22]:
import numpy as np
arr3=np.array([1,2,3,4,5])
print(arr3[1:5])

[2 3 4 5]


In [24]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [26]:
import pandas as np
arr=np.array([2,3,4,6,4,8,9,0,3,1,22,55,88,4,0,5,11,18])
newarr=arr.reshape(2,9)
print(newarr)

<IntegerArray>
[
[2, 3, 4, 6, 4, 8, 9, 0, 3],
[1, 22, 55, 88, 4, 0, 5, 11, 18]
]
Shape: (2, 9), dtype: Int64


In [28]:
import numpy as np
arr2=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr2)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [34]:
import pandas as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a

<IntegerArray>
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
Length: 12, dtype: Int64

In [ ]:
new=a.reshape(2,3,2)
print(new)